TyoajanlaskentaSovellus/Controllers/HenkilotController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace TyoajanlaskentaSovellus.Controllers
{
    public class HenkilotController : Controller
    {
        bool paaKayttaja = true;
        public ActionResult Index()
        {

            scrumDatabaseEntities entities = new scrumDatabaseEntities();
            List<Henkilot> model = entities.Henkilot.ToList();
            entities.Dispose();

            return View(model);
        }

        public JsonResult GetList()
        {
            scrumDatabaseEntities entities = new scrumDatabaseEntities();

            if (paaKayttaja == true)
            {
                var model = (from h in entities.Henkilot
                             select new
                             {
                                 HenkiloId = h.HenkiloId,
                                 Etunimi = h.Etunimi,
                                 Sukunimi = h.Sukunimi

                             }).ToList();
                string json = JsonConvert.SerializeObject(model);
                entities.Dispose();

                return Json(json, JsonRequestBehavior.AllowGet);
            }
            else
            {
                var model = (from h in entities.Henkilot
                             where h.HenkiloId == 1
                             select new
                             {
                                 HenkiloId = h.HenkiloId,
                                 Etunimi = h.Etunimi,
                                 Sukunimi = h.Sukunimi

                             }).ToList();
                string json = JsonConvert.SerializeObject(model);
                entities.Dispose();

                return Json(json, JsonRequestBehavior.AllowGet);
            }



        }

        public JsonResult GetSingleHenkilot(string id)
        {
            scrumDatabaseEntities entities = new scrumDatabaseEntities();

            int HenkiloId = int.Parse(id);

            var model = (from h in entities.Henkilot
                         where h.HenkiloId == HenkiloId
                         select new
                         {
                             HenkiloId = h.HenkiloId,
                             Etunimi = h.Etunimi,
                             Sukunimi = h.Sukunimi
                             
                         }).FirstOrDefault();

            string json = JsonConvert.SerializeObject(model);
            entities.Dispose();

            return Json(json, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Update(Henkilot henk)              
        {
            scrumDatabaseEntities entities = new scrumDatabaseEntities();
            //string id = henk.HenkiloId;

            bool OK = false;

            if (henk.HenkiloId == 0)
            {
                Henkilot dbItem = new Henkilot()
                {

                    Etunimi = henk.Etunimi,
                    Sukunimi = henk.Sukunimi,
                };

                //tallennus tietokantaan
                entities.Henkilot.Add(dbItem);
                entities.SaveChanges();

                OK = true;
                entities.Dispose();
                return Json(OK);

            }
            else //päivitys
            {
                Henkilot dbItem = (from h in entities.Henkilot
                                   where h.HenkiloId == henk.HenkiloId
                                   select h).FirstOrDefault();
                if (dbItem != null)
                {
                    dbItem.Etunimi = henk.Etunimi;     
                    dbItem.Sukunimi = henk.Sukunimi;

                    //tallennus tietokantaan
                    entities.SaveChanges();

                };
                OK = true;
                entities.Dispose();
                return Json(OK, JsonRequestBehavior.AllowGet);


            }

        }

        public ActionResult Delete(string id)
        {
            int HenkiloId = int.Parse(id);

            scrumDatabaseEntities entities = new scrumDatabaseEntities();

            //etsitään id:n perusteella kannasta
            bool OK = false;

            Henkilot dbItem = (from h in entities.Henkilot
                               where h.HenkiloId == HenkiloId
                               select h).FirstOrDefault();
            if (dbItem != null)
            {
                //tietokannasta poisto
                entities.Henkilot.Remove(dbItem);
                entities.SaveChanges();
                OK = true;

            }

            entities.Dispose();
            return Json(OK, JsonRequestBehavior.AllowGet);

        }

    }
}

TyoajanlaskentaSovellus/Controllers/TyotController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Newtonsoft.Json;
using TyoajanlaskentaSovellus;
using TyoajanlaskentaSovellus.Models;

namespace TyoajanlaskentaSovellus.Controllers
{
    public class TyotController : Controller
    {
       
    public ActionResult Update(Tyot tyot)
        {
            scrumDatabaseEntities entities = new scrumDatabaseEntities();

            bool OK = false;

            // onko kyseessä muokkaus vai uuden lisääminen?
            if (tyot.TyoId == 0)
            {
                // kyseessä on uuden asiakkaan lisääminen, kopioidaan kentät
                Tyot dbItem = new Tyot()
                {

                    Tyotunniste = tyot.Tyotunniste,
                    Kuvaus = tyot.Kuvaus,


                };

                // tallennus tietokantaan
                entities.Tyot.Add(dbItem);
                entities.SaveChanges();
                entities.Dispose();
                OK = true;
                return Json(OK, JsonRequestBehavior.AllowGet);
            }
            else
            {
                // muokkaus, haetaan id:n perusteella riviä tietokannasta
                Tyot dbItem = (from t in entities.Tyot
                               where t.TyoId == tyot.TyoId
                               select t).FirstOrDefault();
                if (dbItem != null)
                {
                    dbItem.Tyotunniste = tyot.Tyotunniste;
                    dbItem.Kuvaus = tyot.Kuvaus;

                    // tallennus tietokantaan
                    entities.SaveChanges();
                    entities.Dispose();
                };

                OK = true;
          

                return Json(OK, JsonRequestBehavior.AllowGet);
            }
            

        }
        public JsonResult GetSingleTyo(int id)
    {

        {
            scrumDatabaseEntities entities = new scrumDatabaseEntities();
            var model = (from t in entities.Tyot
                         where t.TyoId == id
                         select new
                         {
                             TyoId = t.TyoId,
                             Tyotunniste = t.Tyotunniste,
                             Kuvaus = t.Kuvaus,

                         }).FirstOrDefault();

            string json = JsonConvert.SerializeObject(model);
            entities.Dispose();

            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }
    
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult Delete(int id)
        {
            scrumDatabaseEntities entities = new scrumDatabaseEntities();

            // etsitään id:n perusteella asiakasrivi kannasta
            bool ok = false;
            Tyot dbItem = (from t in entities.Tyot
                           where t.TyoId == id
                           select t).FirstOrDefault();
            if (dbItem != null)
            {
                // tietokannasta poisto
                entities.Tyot.Remove(dbItem);
                entities.SaveChanges();
                ok = true;
            }
            entities.Dispose();

            return Json(ok, JsonRequestBehavior.AllowGet);
        }
        public JsonResult HaeKaikkiTyot()
        {
            scrumDatabaseEntities entities = new scrumDatabaseEntities();

            var malli = (from t in entities.Tyot
                         select new
                         {
                             TyoId = t.TyoId,
                             Tyotunniste = t.Tyotunniste,
                             Kuvaus = t.Kuvaus
                         }).ToList();

            string json = JsonConvert.SerializeObject(malli);
            entities.Dispose();

            return Json(json, JsonRequestBehavior.AllowGet);
        }
    }
}


    

TyoajanlaskentaSovellus/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title -Tiimi 1</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script type="text/javascript">
        var appInsights = window.appInsights || function (config) {
            function r(config) { t[config] = function () { var i = arguments; t.queue.push(function () { t[config].apply(t, i) }) } } var t = { config: config }, u = document, e = window, o = "script", s = u.createElement(o), i, f; for (s.src = config.url || "//az416426.vo.msecnd.net/scripts/a/ai.0.js", u.getElementsByTagName(o)[0].parentNode.appendChild(s), t.cookie = u.cookie, t.queue = [], i = ["Event", "Exception", "Metric", "PageView", "Trace", "Ajax"]; i.length;)r("track" + i.pop()); return r("setAuthenticatedUserContext"), r("clearAuthenticatedUserContext"), config.disableExceptionTracking || (i = "onerror", r("_" + i), f = e[i], e[i] = function (config, r, u, e, o) { var s = f && f(config, r, u, e, o); return s !== !0 && t["_" + i](config, r, u, e, o), s }), t
        }({
            instrumentationKey: "c463e2d9-de2c-437b-a2a7-6b575f3dfd91"
            });
        window.appInsights = appInsights;
        appInsights.trackPageView();


    </script>
</head>
<body>

  


    <div style="padding-top: 10px;">
        <div class="navbar navbar-inverse navbar-fixed-top">

            <div style="padding: 10px;">

                <div class="container">


                    <div class="navbar-header">


                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">

                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>



                   
                        @Html.ActionLink( " " , "Index" , "Home" , new { style = "background: url('/Img/Careeria_Logo_Valkoinen_2.png') no-repeat center right;display:block; height:49px; width:148px; " } )

                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li>@Html.ActionLink("Etusivu", "Index", "Home")</li>
                            <li>@Html.ActionLink("Henkilöt", "Henkilot", "Home")</li>
                            <li>@Html.ActionLink("Työt", "Tyot", "Home")</li>
                            <li>@Html.ActionLink("Tunnit", "Tunnit", "Home")</li>
                            <li><a href="~/Raportti.aspx">Raportointi</a></li>
                        </ul>
                        @Html.Partial("_LoginPartial")
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Tiimi 1</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>